---
#tasks file for role

- name: install stuff which allows apt to use repositorys over https
  become: true
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add dockers official gpg key
  become: true
  apt_key:
    keyserver: "{{ docker_gpg_server }}"
    id: "{{ docker_gpg_key }}"

- name: Get release
  become: true
  command: lsb_release -cs
  register: command_release
  changed_when: (command_release.stdout != 'stretch') and (command_release.stdout != 'jessie')

- name: add debian repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ command_release.stdout }} stable
    state: present
    filename: 'docker'

- name: install docker-ce
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    force: yes

- name: "enable and start docker service"
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
